### DISCUSSION TITLE
Docker Builds with TurboRepo

### DISCUSSION THREAD

**Discussion by rcronin** [rharkor/caching-for-turbo#246] [Q&A] [answered]
On the turborepo website, they mention it's possible to use remote caching with docker builds.

https://turbo.build/repo/docs/guides/tools/docker#remote-caching

Was curious if anyone has used this action to try to attempt this with github actions?

**Comment by rharkor** [comment]
Hey yep, I'm using it. On my project I build the packages inside docker with the turbo cache using my GitHub actions

**Comment by rcronin** [comment]
Do you mind sharing how you’ve done this?

Ryan Cronin

Sent from my iPhone
________________________________

**Comment by rharkor** [comment, marked as answer]
This is how to use the cache within docker

This is the part in the github action:

```yml
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.8
        with:
          provider: s3
          max-age: 1mo
          max-size: 10gb
          s3-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          s3-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          s3-bucket: ${{ secrets.NEXT_PUBLIC_S3_BUCKET_NAME }}
          s3-region: ${{ secrets.S3_REGION }}
          s3-endpoint: ${{ secrets.S3_ENDPOINT }}

      - name: Build docker image
        timeout-minutes: 10
        run: |
          docker build --build-arg TURBO_TEAM=$TURBO_TEAM --build-arg TURBO_TOKEN=$TURBO_TOKEN --build-arg TURBO_API=$TURBO_API --network=host -t ${{ secrets.REGISTRY_URL }}/internal:latest -f apps/internal/docker/internal.Dockerfile .
```

And in my dockerfile

```dockerfile
FROM base AS builder

ARG TURBO_TEAM
ENV TURBO_TEAM=$TURBO_TEAM

ARG TURBO_TOKEN
ENV TURBO_TOKEN=$TURBO_TOKEN

ARG TURBO_API
ENV TURBO_API=$TURBO_API

RUN turbo run build
```

Please note that the s3 provider and configuration for `rharkor/caching-for-turbo` is optional you can keep the github cache by default
