### ISSUE TITLE
Unable to retrieve cached items when turbo is called with --dry-run

### ISSUE THREAD

**Issue by Palaxx** [rharkor/caching-for-turbo#251]
Hello,

I'm trying to use `caching-for-turbo` in my CI pipelines but I've some problem when the cache is retrieved during a dry-run execution. 

Executing a turbo command with the dry-run options seems to cause a 500 statusCode in the `GET /v8/artifacts/:hash` endpoint.
I see the following logs in my ci:
```json
{"level":30,"time":1740433775553,"pid":43,"hostname":"docker-desktop","reqId":"req-3","msg":"Cache lookup for turbogha_b1ea68acb6cd428b"}
{"level":30,"time":1740433775567,"pid":43,"hostname":"docker-desktop","reqId":"req-3","msg":"Sending artifact for b1ea68acb6cd428b"}
{"level":50,"time":1740433775567,"pid":43,"hostname":"docker-desktop","reqId":"req-3","req":{"method":"HEAD","url":"/v8/artifacts/b1ea68acb6cd428b?slug=turbogha","hostname":"localhost:41230","remoteAddress":"::1","remotePort":55506},"res":{"statusCode":500},"err":{"type":"TypeError","message":"The \"string\" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of ReadableStream","stack":"TypeError: The \"string\" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of ReadableStream\n    at new NodeError (node:internal/errors:405:5)\n    at Function.byteLength (node:buffer:779:11)\n    at Object.headRouteOnSendHandler (/run/act/actions/rharkor-caching-for-turbo@v1.6/dist/node_modules/fastify/lib/headRoute.js:17:1)\n    at next (/run/act/actions/rharkor-caching-for-turbo@v1.6/dist/node_modules/fastify/lib/hooks.js:295:1)\n    at onSendHookRunner (/run/act/actions/rharkor-caching-for-turbo@v1.6/dist/node_modules/fastify/lib/hooks.js:317:1)\n    at onSendHook (/run/act/actions/rharkor-caching-for-turbo@v1.6/dist/node_modules/fastify/lib/reply.js:555:1)\n    at Reply.send (/run/act/actions/rharkor-caching-for-turbo@v1.6/dist/node_modules/fastify/lib/reply.js:178:1)\n    at Object.<anonymous> (/run/act/actions/rharkor-caching-for-turbo@v1.6/dist/src/lib/server/index.ts:67:1)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","code":"ERR_INVALID_ARG_TYPE"},"msg":"The \"string\" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of ReadableStream"}
```

The same command without dry-run correctly find the data from cache.

I'm replicate locally using act `act --container-architecture linux/amd64 -W '.github/workflows/monorepo.yml'`

but the same issue occurs in real github workflow.

You should be able to reproduce using the following workflow
```
on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
  workflow_dispatch:
    
permissions:
  contents: "write"
  pull-requests: "write" #
  id-token: "write"

name: NodeJS monorepo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.6
      - uses: pnpm/action-setup@v3
        with:
          run_install: true
          version: 8.15.5
      - run: pnpm exec turbo build --dry-run json
      - run: pnpm exec turbo build

```
