### ISSUE TITLE
AWS auth does not work with assumed role

### ISSUE THREAD

**Issue by karelbemelmans** [rharkor/caching-for-turbo#309]
I've tried to use the action with the OIDC role we have configured for our repository, but it doesn't work.
If I switch to an IAM user it does work:

```yaml
- name: Configure AWS credentials
  id: aws-credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: 'REDACTED'
    aws-region: 'eu-central-1'
    output-credentials: true

- name: Cache for Turbo
  uses: rharkor/caching-for-turbo@v1.8
  with:
    cache-prefix: turbogha_ # Custom prefix for cache keys
    provider: github # Storage provider: 'github' (default) or 's3'

    s3-access-key-id: ${{ steps.aws-credentials.outputs.aws-access-key-id }}
    s3-secret-access-key: ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
    s3-bucket: REDACTED
    s3-endpoint: https://s3.amazonaws.com
    s3-region: eu-central-1
```

When using this way of temporary credentials you often need to pass in the session token (`AWS_SESSION_TOKEN`) as well, so I guess that is one input you can add to make this work.

An even nicer to have would be if you discover these env variables automatically, since the configure-aws-credentials sets them after having successfully assumed the OIDC role.
